version : "3.8"

services :

    postgres:
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        - DATABASE_HOST=127.0.0.1
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root

    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
      ports:
        - "80:80"
      depends_on:
        - postgres
    
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5000:5000"  # Puertos para exponer tu aplicación
      depends_on:
        - postgres